apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
  labels:
    app: scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: scanner
        image: "docker.io/schramek/clamav-scanner:5"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3310
        volumeMounts:
        - name: scanner-signature-updates
          mountPath: /var/lib/clamav
      volumes:
      - name: scanner-signature-updates
        persistentVolumeClaim:
          claimName: scanner-signature-updates
---
apiVersion: v1
kind: Service
metadata:
  name: scanner
spec:
  selector:
    app: scanner
  ports:
  - port: 3310
    targetPort: 3310
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanner-signature-updates
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
